services:
#  manager:
#    build: manager
#    ports:
#      - '2323:2323'
#    depends_on:
#      - postgres
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/photo_arxiu


  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=photo_arxiu'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
