server:
  port: 2323

spring:
  application:
    name: manager


  datasource:
    url: jdbc:postgresql://localhost:5432/photo_arxiu
    driverClassName: org.postgresql.Driver
    username: myuser
    password: secret